version: '3.9'

services:
  activemq:
    image: symptoma/activemq:latest
    container_name: 'activemq'
    ports:
      - '8161:8161'
      - '61616:61616'
    volumes:
      - ./data/activemq/data:/data/activemq
      - ./data/activemq/log:/var/log/activemq